### ISSUE TITLE
Remove explicit op_type=create

### ISSUE THREAD

**Issue by darkoc** [elasticsearch/elasticsearch-river-twitter#70]
When running multiple Twitter Rivers which fill the same ES index, there is a possibility that the rivers will fetch the same Twitter status with different tracking keywords. The Twitter River uses op_type=create which causes the bulk operation to report a warning: "There was failures while executing bulk". It seems unnecessary that the op_type is create. 
In my scenario receiving the same tweets from different rivers occurs very frequently and it pollutes the logs. Can the op_type=create be removed?

**Comment by dadoonet** [comment]
True. Issue still exists when using `raw` option. Will push a new fix.
