### ISSUE TITLE
Maven doesnt work with the configured repostiory

### ISSUE THREAD

**Issue by Vineeth-Mohan** [elasticsearch/elasticsearch-river-twitter#84]
<repositories>
        <repository>
            <id>sonatype</id>
            <url>http://oss.sonatype.org/content/repositories/releases/</url>
        </repository>
    </repositories>

Only after removing this , maven actually works.

**Comment by dadoonet** [comment]
Thanks @Vineeth-Mohan 

It has been removed starting branch 1.x (and master). See https://github.com/elasticsearch/elasticsearch-river-twitter/commit/72b63984f882a5cbe92c2a9830b75fd381cf36d3#diff-600376dffeb79835ede4a0b285078036L45

Closing.
