### ISSUE TITLE
plugin trouble: Plugin installation assumed to be site plugin, but contains source code, aborting installation.

### ISSUE THREAD

**Issue by OuesFa** [elasticsearch/elasticsearch-river-twitter#85]
Hi,
I'm on ES-1.4.1.
I'd like to add River-Twitter Plugin.
I'm behind a proxy, so i download the archive then i try ( plugin --install river-twitter --url "file:\\\E:\elasticsearch-river-twitter-2.4.1.zip" )
it worked fine for ES-head and Marvel, but not in this case, i have this error.

![capture](https://cloud.githubusercontent.com/assets/10348298/5664930/8ab9beda-9754-11e4-89c9-687b0cd2858a.PNG)
Need help please !

**Comment by dadoonet** [comment]
What gives then `bin\plugin --list`?

**Comment by OuesFa** [comment]
Thanks for fast response :)
It gives : 
Installed plugins:
-head
-marvel

**Comment by dadoonet** [comment]
From which URL did you download `elasticsearch-river-twitter-2.4.1.zip`?

**Comment by OuesFa** [comment]
This one
https://github.com/elasticsearch/elasticsearch-river-twitter/archive/v2.4.1.zip

Wrong link ?

**Comment by dadoonet** [comment]
Yeah. It's a github archive. Not the final artifact. Pleas download it from: https://download.elasticsearch.org/elasticsearch/elasticsearch-river-twitter/elasticsearch-river-twitter-2.4.1.zip

**Comment by OuesFa** [comment]
Worked fine, thank you so much :)
