### ISSUE TITLE
Twitter River Don't Work [ Index Missing Exception ]

### ISSUE THREAD

**Issue by adnanjabbar** [elasticsearch/elasticsearch-river-twitter#88]
Tried installing twitter river plugin on Elasticsearch on Google Cloud but no luck after completing the successful loading PUT and GET commands when it came the time to get ```http://localhost:9200/twitter_river/_search ```
it gave a result of 

```json
{
    "error": "IndexMissingException[[river_twitter] missing]",
    "status": 404
}
```

Help needed.

**Comment by dadoonet** [comment]
May be you could try to give all details of what you did so far?
Hard to say without any clue.

**Comment by adnanjabbar** [comment]
Step 1 : Installing ElasticSearch "Click to Deploy" option via Google Cloud on 3 Nodes VM's
Step 2 : Got a positive result on a GET call via Postman on the http://IPAddress:9200 
as following : 

{
  "status" : 200,
  "name" : "elasticsearch-4nyc",
  "cluster_name" : "elasticsearch-cluster",
  "version" : {
    "number" : "1.4.2",
    "build_hash" : "927caff6f05403e936c20bf4529f144f0c89fd8c",
    "build_timestamp" : "2014-12-16T14:11:12Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.2"
  },
  "tagline" : "You Know, for Search"
}

After that opened SSH client and went to the directory
/usr/share/elasticsearch$ 
ran command of 
sudo bin/plugin -install elasticsearch/elasticsearch-river-twitter/2.4.1
Response : Installed
then opened postman (Google Chrome)
selected URL : http://localhost:9200/_river/twitter_river/_meta
Selected POST (JSON) and posted following

{
    "type" : "twitter",
    "twitter" : {
        "oauth" : {
            "consumer_key" : "(****KEY****",
            "consumer_secret" : "***KEY***",
            "access_token" : "***KEY***",
            "access_token_secret" : "***KEY***"
        }
    },
    "index" : {
        "index" : "twitter_river",
        "type" : "status",
        "bulk_size" : 100,
        "flush_interval" : "5s"
    }
}

***KEY*** was replaced with original values

after that  I got a response of following 

{
    "_index": "_river",
    "_type": "twitter_river",
    "_id": "_meta",
    "_version": 1,
    "created": true
}

after that I opened up the following url via GET command in Postman

http://localhost:9200/twitter_river/_search

and got error 

{
    "error": "IndexMissingException[[twitter_river] missing]",
    "status": 404
}

I restarted the Elasticsearch using the command
sudo service elasticsearch restart
everything responded OK

I again tested the GET command and even on browser 
it gave me the same error of

{
    "error": "IndexMissingException[[twitter_river] missing]",
    "status": 404
}


I'm a n00b, but hope I still have explained my steps properly.

**Comment by adnanjabbar** [comment]
Wherever I have used localhost it's a server IP sorry was being a bit generic in my explanation.

**Comment by adnanjabbar** [comment]
I copied every step also via the video on Youtube : https://www.youtube.com/watch?v=6swzc_XA-j8
and still got the same error.

**Comment by adnanjabbar** [comment]
OK before that I was restarting 1 node on ElasticSearch Cluster now its a different response when I restarted all 3 nodes one by one

The response is  : 

{
    "took": 17,
    "timed_out": false,
    "_shards": {
        "total": 5,
        "successful": 5,
        "failed": 0
    },
    "hits": {
        "total": 0,
        "max_score": null,
        "hits": []
    }
}

**Comment by adnanjabbar** [comment]
Issue Fixed
