### ISSUE TITLE
Sentiment analysis on tweets

### ISSUE THREAD

**Issue by OuesFa** [elasticsearch/elasticsearch-river-twitter#93]
Hi :)

I have an elasticsearch cluster which is using twitter river to download tweets. I would like to add a sentiment analysis module which takes each tweet and computes a score (+ve/-ve) etc and then visualize using Kibana.

There are python/java codes that computes such scores. But how to call these scripts with river-twitter.
Is there a way to do sentiment analysis with river-twitter for now ?

Thank you !

**Comment by dadoonet** [comment]
I'm not aware of this but for sure if it will happen, it will most likely something that could be a logstash filter.
